### ISSUE TITLE
run-updater.bat not working

### ISSUE THREAD

**Issue by redtrillix** [rejetto/hfs#114]
**Describe the bug**
With the updater batch script, you cant auto update as it cant read the config file and uses a different directory located at `C:\Users\<user>\.hfs`, this means that it tries to run with a different port and config than what is in use by hfs.exe.

**To Reproduce**
1. Go to the hfs.exe location.
2. Click on run-updater.bat (or right click and run as administrator, it makes no difference).
3. It shows that its using a different port and file location.

**Expected behavior**
Its suppose to use the config already in use by hfs.exe instead of making a new directory and config.

<details>
<summary><b>Click for Screenshots</b></summary>
      
running hfs.exe:   
![image](https://user-images.githubusercontent.com/54786587/220556264-1a97552b-5159-4e1a-bf84-326506954b6c.png)

running run-updater.bat:
![image](https://user-images.githubusercontent.com/54786587/220556708-d33aa240-cee6-4f43-a3b0-a50dc2594726.png)
![image](https://user-images.githubusercontent.com/54786587/220556985-26b726a6-cc54-43f4-a7c4-3960de04a3a0.png)

</summary>
</details>

**Environment (please complete the following information):**
 - OS: Windows Server 2022 Standard 21H2
 - Browser: n/a
 - Version: HFS 0.36.0

**Comment by redtrillix** [comment]
forgot to add, I also have the same results if i have `hfs.exe-new` and `hfs.exe-old` as specified in the batch file

**Comment by redtrillix** [comment]
For more information:
Running a command like `config port <port>` will also create a config in the other directory as shown below.

<details>
<summary>Screenshots</summary>

(running the command `config port 4000`)
![image](https://user-images.githubusercontent.com/54786587/220581485-f02bba31-5cb0-4837-ba94-58c1e3d8369e.png)

</details>

**Comment by redtrillix** [comment]
CLOSED: Fix implemented in release [v0.37.0](https://github.com/rejetto/hfs/releases/tag/v0.37.0) | https://github.com/rejetto/hfs/commit/05a89616864257a9d8e5aa0a2b7b6a2217713b65

**Comment by rejetto** [comment]
I was actually wondering if anyone was using this method. 😀 I've used it for a few months, but then switched to npm installation (which is not supported by it).
You may have read that is just an experiment, and there is another experimental method available: entering "update" in the console where you launch hfs. The latter is quite different because it will also download the update (if any).
Apparently very convenient but not suitable for running as a service, and I was under the impression that it works only once, and the next update won't work until you restart hfs manually (needs further testing).
I'm still not sure what will/should be the method for updating, but I think it's a quite important matter, especially in this phase when we have frequent releases.
Further study is required.

**Comment by redtrillix** [comment]
I haven't updated yet, but ill let you know how it works when i get some time.

**Comment by redtrillix** [comment]
I might be wrong, but the update script seems to be working as intended. 
Thanks for the fix.
