### ISSUE TITLE
Base URL change is partially ignored

### ISSUE THREAD

**Issue by Null-Kelvin** [rejetto/hfs#140]
Changing the Shared Files - Home - Link does nothing

**To Reproduce**
1. Open admin settings, go to "Shared files"
2. Click on Home
3. Click to change button
4. Set URL field like 192.168.1.2:8090/hfs

**Expected behavior**
Files must be available on http://192.168.1.2:8090/hfs/
instead they available only on http://192.168.1.2:8090/

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version: HFS 0.38.2

**Comment by rejetto** [comment]
thanks for reporting.
the problem is that this field is not clear enough.
It's not clear what it is for, and it's not preventing you from entering wrong characters.
I'm going to improve it like this
1. the name will be "Custom IP or domain"
2. the text under the field will become something like:
_You can type any address but you are responsible to make the address work. This functionality is just to help you copy the link in case you have a domain or a complex network configuration._
3. I will prevent typing invalid characters like /
<img width="646" alt="image" src="https://user-images.githubusercontent.com/1367199/224021391-69933b6b-06b0-47a2-a897-d9b209728eeb.png">


please tell me if it is clear to you like this, and feel free to suggest other improvements

**Comment by Null-Kelvin** [comment]
To avoid the XY problem I just describe what I want to achieve :)
I need to put HFS behind nginx in specific location. Nginx must do TLS, HTTP/3 and client certificate authentication, HFS just do what it does best: serving files from a Windows machine.
The thing is - I can't get it to work this way. If in old HFS this can be done by redacting template and rewrite rule in nginx, the new one is dangerously near to zeroconf. Of course, I can create a `/hfs/` folder in HFS, but it's not working either - CSS and JS served from `/~/` so I need another rewrite rule, but successful login redirects me to site main page and I need to go to the hfs again.
I assumed, that "base url" field must set as base exactly what I type there, and change HFS main location to `/hfs/` and auxiliary `/~/` to` /hfs/~/` 
Wouldn't that make the HFS more flexible in its application?

**Comment by rejetto** [comment]
oh, i see!
this is a use case I didn't consider yet, being reverse-proxied as a path.

So you have your nginx already configured to remove the /hfs from the url as it forwards the request, and this is probably enough for downloading single files but not for the whole browsing experience.

Anyway, the "link" feature we were talking about wasn't meant  to affect serving. It's just a utility to make text links intended to be copied.
As I work to support this use-case I don't exclude changing its meaning, but I may need to introduce another option instead.

Best thing would be to reproduce your case. Would you provide your nginx rules, just to be sure?

"Redacting template" as it was in HFS 2.3 turned out in a poor technical choice, that could easily lead to malfunctioning, security problems and impossibility to update. Sure it gave you a lot of power but the price was too high IMO. That's why I'm taking a different approach now.
There are less options for the moment, but I will try to add more as I understand they are needed, but sometimes leaving it to plugins. I count on people like you to make me understand what's needed, and possibly on other fellow programmers to help also with the making.

**Comment by Null-Kelvin** [comment]
>this is probably enough for downloading single files but not for the whole browsing experience.

Yes, exactly! Without browsing experience it's just static file serve, without able to login, upload and stuff :)

>I may need to introduce another option instead

That would be great!

>Would you provide your nginx rules, just to be sure?

```
server {
 listen 443 quic;
 listen 443 ssl http2;
 server_name example.com

    root /var/www/html;
    index index.html;

 include ssl.conf; # ssl options and certs

    # Rewrite rule for HFS static files
    rewrite /~(.*) /hfs/~$1;

# HFS SERVER

    location /hfs/ {
        proxy_http_version 1.1;
        keepalive_timeout 30;
        proxy_buffering off;
        proxy_redirect off;
        proxy_max_temp_file_size 0;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass      http://192.168.1.8:8088/;
        if ($request_method !~ ^(GET|HEAD|POST)$ ) { return 405; }
    }
}
```
That work with HFS 2.4.0 RC7 if I change `%bread-url%` to `hfs%bread-url%`
With new version I get page rendered, and can browse - but link's are not working, they lead to `http://example.com/file.zip` instead of `http://example.com/hfs/file.zip`

>I count on people like you to make me understand what's needed

There was a discussion thread about reverse proxy on [your old forum](https://rejetto.com/forum/index.php?topic=13059.0), so I think that it would be a useful option.

Anyway, thank you for a great program. I have been using HFS for almost 12 years now - that's really one of most long-lived programs on my PC :)

**Comment by rejetto** [comment]
awesome :)

and what if I told you I think I'm done, and you won't even need the "rewrite" line?
and it will be like you imagined it, you just change the link in that dialog.
I would like you to give it a try before release, it's working like a charm here but maybe you have something different there.
Would you?

**Comment by Null-Kelvin** [comment]
Gladly! :)

**Comment by rejetto** [comment]
very well!
instructions
1. remove the rewrite line
2. add these line inside the "location /hfs/" block

            proxy_set_header        X-forwarded-prefix "/hfs";
            client_max_body_size    10000M;

[0.39.0-alpha1](https://github.com/rejetto/hfs/files/10946491/hfs-windows.zip)

**Comment by Null-Kelvin** [comment]
Nice, no problem so far, work exactly as expected!

**Comment by rejetto** [comment]
i'm going to publish this as example in the readme

```
location /files/ {
  proxy_http_version 1.1;
  keepalive_timeout 30;
  proxy_buffering off;
  proxy_redirect off;
  proxy_max_temp_file_size 0;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;  # forward IP address
  proxy_set_header        X-forwarded-prefix "/files"; # the location without final slash
  client_max_body_size    0;  # disable max size for uploads
  proxy_pass      http://127.0.0.1:80/;
}
```

**Comment by rejetto** [comment]
i will also let you select the protocol

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1367199/224505482-6d8dea2c-01c4-4e34-ba02-de89d53d9e3e.png">
