### ISSUE TITLE
Problems with handling single quotes?

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#160]
```onclick='videoplay("${entry.n}")'``` will not be executed properly, ending on ```videoplay("```?

**Comment by rejetto** [comment]
try this way
`onclick="videoplay(${JSON.stringify(entry.n)})" `

**Comment by SanokKule** [comment]
Now it gets passed empty string i think
`Uncaught SyntaxError: Invalid or unexpected token (at (index):1:11)`
`videoplay()`
Only on files with single quotes in the name.

**Comment by rejetto** [comment]
well, i experimented a bit, and the correct way should be

    `<button onclick='videoplay(${JSON.stringify(entry.n).replace(/'/g, '&apos;')})'>+</button>`

Please confirm it works for you.
It is rather complicated, I know, so I decided that from next version you'll be able to do this

    HFS.onEvent('afterEntryName', ({ entry }, { _ }) =>
        `<button onclick='videoplay("${_.escape(entry.n)}")'>+</button>`)

Anyway, this problem is due to the fact that we are trying to produce correct HTML.
The plugin can generate content as HTML, but also with [pure javascript or React](https://github.com/rejetto/hfs/blob/main/dev-plugins.md#javascript).
In fact, my simple-player plugin has no such problem, as it works with react

    h('button',{ className: 'play-button', onClick: () => play(entry.n) }))
