### ISSUE TITLE
requirements like from old version v2.3

### ISSUE THREAD

**Issue by gogi100** [rejetto/hfs#169]
can you add settings like from old version the hfs 2.3 like:

1. speed limit for single address
2. max simultaneous download
3. max simultaneous downloads from single address
4. max simultaneous addresses
5. max simultaneous addresses downloading
6. max connections
7. max connections from single address
8. connections inactivit timeout
9. stop spiders

![settings](https://user-images.githubusercontent.com/21057856/226823183-d36ad968-9355-4faf-98d9-b05d5e8c822c.jpg)

**Comment by rejetto** [comment]
premise: having many options is not good. People get confused, and maintenance of the project gets harder.
Therefore adding options must be repaid by clear usefulness.

1 it's already available

2+3+4+5
I don't see what they are good for. At the time I made these options without thinking much, just because it was possible, but now I cannot think of good reasons to have these when you have limit-per-ip.

6+7
i'm not sure if these could actually be any good. Can someone make examples where these would actually solve a problem? I'm thinking of ddos attacks, but I not even sure that they would solve anything.

8
this is very easy to make, but can you tell me how you would benefit from this?

9
i will add this to the to-do list. In the meantime you can get the same feature by adding a hidden file "robots.txt" in the root, with this content
```
User-Agent: *
Disallow:
```

**Comment by xz00311** [comment]
I hope that the language can also be set on the background webpage

**Comment by gogi100** [comment]
the goal of these settings is that if I have a lot of users uploading files, they can slow down the server: with the number of connections, upload speed, etc.

**Comment by rejetto** [comment]
i don't see how the number of connections could help you in this case.
Your bandwidth may be saturated even with 1-2 connections.
Ok for "Upload speed", but it's not in your list. Such limit never existed in HFS.
I already considered it, and I hope to be able introduce it in the future, but it's not a quick job.

**Comment by W-i-n-7** [comment]
> can you add settings like from old version the hfs 2.3 like:
> 
>     1. speed limit for single address
> 
>     2. max simultaneous download
> 
>     3. max simultaneous downloads from single address
> 
>     4. max simultaneous addresses
> 
>     5. max simultaneous addresses downloading
> 
>     6. max connections
> 
>     7. max connections from single address
> 
>     8. connections inactivit timeout
> 
>     9. stop spiders
> 
> 
> ![settings](https://user-images.githubusercontent.com/21057856/226823183-d36ad968-9355-4faf-98d9-b05d5e8c822c.jpg)

what os is that? looks like windows server 2003

**Comment by rejetto** [comment]
just published "stop spiders" plugin
