### ISSUE TITLE
FEATURE: hope owner add VI (vietnam) as Embedded language

### ISSUE THREAD

**Issue by BussyBakks** [rejetto/hfs#263]
can you add VI as Embedded language?
file: [hfs-lang-vi.json, edit to .json to import](https://github.com/rejetto/hfs/files/11707310/hfs-lang-vi.txt)
pls, i spend 1DAY for this
COPYRIGHT BY THENOOPY12 (Nguyễn Văn Ngu)
SCREENSHOTS:
![image](https://github.com/rejetto/hfs/assets/108082159/73815cb0-cff7-4771-b61c-515c3d8a2396)
![image](https://github.com/rejetto/hfs/assets/108082159/2b8c36fb-ef1c-4658-b294-0e56a1a3c5dc)
![image](https://github.com/rejetto/hfs/assets/108082159/b2dc57af-6057-41b7-9960-e8237be6a17d)

**Comment by rejetto** [comment]
yeah, sure, and thank you for your contribution.
There are still some things that need to be fixed. Please, let me help you.

I noticed you didn't translate these type of messages
  >        "n_folders": "{n,plural,one{# folder} other{# folders}}",
I guess it's because the syntax is complex.
*n,plural* is a special command to handle text that can be different when the number of folders change (for example).
I don't know your language, but tried to make a possible translation. What do you think of this?
> {n,plural,other{# thư mục}}

this becomes: 1 thư mục, 2 thư mục, 3 thư mục....
it makes no difference with different numbers. Is it correct?

**Comment by BussyBakks** [comment]
yeah but thanks for respond!

**Comment by BussyBakks** [comment]
uh, do i post my langs file to [langs repo](https://github.com/rejetto/hfs/tree/main/src/langs)?

**Comment by rejetto** [comment]
just attach your file here as you already did, when you have corrected the errors.
I will take care of the rest.

Please use my example above to understand how to write the translations for {n}
I noticed the problem is affecting at least these entries:
- n_files
- n_folders
- filter_count
- select_count
- delete_confirm
- delete_failed
- send_files

I asked chatGPT to translate, and while it is possibly wrong you may use its output as inspiration for your corrections 🙂
```json
"n_files":"{n,plural,one{# tập tin}other{# tập tin}}",
"n_folders":"{n,plural,one{# thư mục}other{# thư mục}}",
"filter_count":"{n,plural,one{# đã lọc}other{# đã lọc}}",
"select_count":"{n,plural,one{# đã chọn}other{# đã chọn}}",
```

**Comment by rejetto** [comment]
i didn't receive any update on this.
the last version i got from you has the problems that i mentioned. Not only those 4 lines, but all the lines with the {n}.

**Comment by BussyBakks** [comment]
@rejetto i finish my work in past, i forgot to up, srr 4 waiting
here ====> 
[hfs-lang-vi.txt](https://github.com/rejetto/hfs/files/11861744/hfs-lang-vi.txt)

**Comment by rejetto** [comment]
thanks! included in next release
