### ISSUE TITLE
Log entry for successful downloads 

### ISSUE THREAD

**Issue by Athep** [rejetto/hfs#268]
I posted the below in discussions. Maybe the wrong place. Anyway:

As it is now, hfs logs all downloads with status code 200, even if unsuccessful. It is not possible to tell if a file is fully downloaded or not.

Is it possible to implement a function that shows log entries for successful downloads, like "Fully downloaded" as in the old version 2.3?

**Comment by rejetto** [comment]
Code 200 is the response of the server, and it's HTTP standard.
The HTTP code says nothing on what happens "after", so there's no such code like a "the browser disconnected in the middle of the download". Even the size, is not the size actually downloaded, but the size that was agreed for the download.

Note: if a user is using a download manager, it will generate even 5 different requests for a single download, because download is split in parts.

This is not ideal for all users, and I already noticed this problem, but it's a bit tricky, because HFS 3 is producing "apache" standard log.
The reason for using the standard is because so you can use a lot of existing software for statistics.
So, before introducing extra information I have to undestand what's the best way to do it without breaking compatibility.

I'm considering introducing an extra column with a "description" by HFS on the same log entries that actually completed the dowload, but I have to consider other possibilities, like generating a separated log entry (with a fake code number to avoid confusion and double counting in statistics), or even a separated log file.

**Comment by rejetto** [comment]
If you take some time to describe exactly, in details, how you imagine the feature to work, it would be useful.
The more I understand your needs, the more I will design a proper functionality.

**Comment by rejetto** [comment]
see #334
