### ISSUE TITLE
Delete enable tile mode in file menu?

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#304]
It seems to me that turning on the tile mode in the file menu means that it should be deleted. This is still a display option that includes menu options, the file menu should carry a particularly thorough study of the file.

**Comment by rejetto** [comment]
so, you are talking about the "Enable tiles mode" of the thumbnails plugin.
I'm not sure what you mean, tho.
You don't like it and want to remove it?

**Comment by 6elkir** [comment]
Yes, I mean exactly it) It is convenient, but turning it on / off is more logical link completely in the options menu, and not in the file menu. The file menu should be put into effect on the file we clicked on (like the right key in Windows) changing the folder view is a setting for the folder and it makes more sense to use it frequently in the options menu. As a rule, since we already have so many options and uses, I think it's time to switch to something similar to the Windows Explorer panel, and not hide everything from the menu is not required)

**Comment by rejetto** [comment]
you are perfectly right, but there's a reason why I put it there.
Imagine: the user installs the thumbnails plugin, he expects "big" thumbnails automatically, but he sees instead very small thumbnails in list mode.
It's very likely that he will not think about going in options and enabling "tiles".
I think this will happen to a lot of people. So, instead of letting them down, I decided to add this shortcut in the file menu, because it's very hard to miss (unlike the options dialog). 
Maybe I will find a better way, but until then I'll keep it.

Anyway, the option is there only if you are NOT already in tiles mode, and only for files with thumbnails. So, it's not always there.

You understand that this is not part of HFS, but the plugin, right?

**Comment by 6elkir** [comment]
Understand. It seems to me that instead of determining where the user will stumble upon the desired setting, it is easier to switch to the interface familiar to everyone in windows | linux | mac, everywhere in file managers there is a panel on top where all this is located, we also have it, but tucked away in buttons, I would bring it to a menu/or buttonbar/ribbon view. Variants of the presented files and their appearance can be placed on a possible panel ala Tiles, List Chess Icons, List

**Comment by rejetto** [comment]
i'm not sure I got all of what you are suggesting, but the changes don't seem trivial.
I've found another solution that should be good enough: make it as an option that you can disable.
You'll find an update for the plugin (version 1.1)
<img width="479" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/32d9168b-4408-4f66-b04e-8d9e6c6fa6f1">
