### ISSUE TITLE
Updated translation for French v0.47.1

### ISSUE THREAD

**Issue by Microtel27200** [rejetto/hfs#318]
Hello
I updated the json file :
[hfs-lang-fr.zip](https://github.com/rejetto/hfs/files/12326867/hfs-lang-fr.zip)

I also found one popup not translated : 

![Capture](https://github.com/rejetto/hfs/assets/131811950/621e648f-2c85-4466-b2d1-3292e208b465)

Best regards
Jacques - Microtel Club Vernon

**Comment by rejetto** [comment]
merci beacoup for your update!
that message you say it's part of a plugin.
At this very moment it's plugin's fault that didn't make the text translatable, but that's easily correct, since I'm the author of that plugin 🙃
Ok, just published update for that plugin.
Technically, a translation file can include text of plugins as well without distintion.
But I fear that if I don't make some distinction we'll have have a mess later.
I'm still not sure what's best to organization to translate plugins, but I'm making this attempt: [please see here](https://github.com/rejetto/hfs/commit/d449954ade502c1df98f48c5e1a6699de00b6ffa).

**Comment by SanokKule** [comment]
> I'm still not sure what's best to organization to translate plugins

Does having separate translation files in plugin's folder `plugin-name/lang` sound reasonable?

**Comment by rejetto** [comment]
the problem of data organization is strictly related to the responsability of the translation.
Who's going to take care of the translations? Is the same person translating HFS supposed to look at the plugins? Sounds like too much to ask.
Nonetheless, it is possible for him. I made an attempt if you look at the link in my previous post.
At the moment there's no technical need in separation with plugins, so I just made up a separation that's good for the translation author, to keep the work organized.
Anyway, it may be a good option to let a plugin carry its own translation files as an extra option. Maybe as a single json file that contains mutiple languages, since its needs may be different.
