### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#37]
I have some small questions, and I want to know more about the details:

**1st**

In current repo state code I see Plugin description string should have double quotes.
I also see in code it's for getting description from disabled plugins, without executing them.
I also guess it's for not escaping single quotes. But in this case escaping double quotes won't work, instead...
In my mind a better alternative is backtick &#96;`'any' "string"`&#96;. Multiline flag maybe also used in that regexp.
Of course tell plugin developers don't use `${}`
btw single quote is my code style :)

**2nd**

Readme say Plugin middleware function could return another function for "executing in upstream".
I found it's just executing the returned function at the very end of plugin cycle.
Think of there can be multiple middlewares, that do different things. We also need correct order.
Is the "upstream" used to do that? I feel not enough...

**3rd**

What's the supposed way to let a plugin handle authentication? (or should not do it?)
I can't directly get it. Since it's about security, please take consideration :)

**4th**

Every time I want to sync HFS repo, I `pull` it but always resulting in file conflict. Notably the 1.4MiB `package-lock.json`
(I didn't change any dev file manually)
Suggested by git, I just committed a change. But it result in many other dev files can't be merged.
That's even more messy, and what I could do is `rm -rf hfs` then `git clone` it again.
This time, in fresh repo I put a `*` in `.gitignore`. I don't know if it would work...
Any suggestion?

**The last**

Consider a user guide? Put "Quick Start" in readme, and detailed "Cookbook" and "Dev Guide" in elsewhere.
I can help it if I have time :)
Many one say HFS 3 is not user friendly. Though I get no point about this...

*Well, that's all...*

Oh wait, is such kind of things suitable in Discussion?

**Comment by rejetto** [comment]
next time open multiple "issues", otherwise it's harder to answer to all questions, or to answer 1 and then remember to answer the rest 😉

1. I considered backticks at the time, but it would be inconsistent, because I don't want to support ${} and people are required to know that they don't have to use it. As a side note, it is newer and less people know it.
Double quotes is
- consistent with what I wrote in `dev-guidelines` file
- easier to read
- easy to unescape with JSON.parse
- convenient with english, because single quote is more frequent
 
note: single-quote is my coding style too

2. upstream has little to do with plugins. If you think of calling multiple functions (plugins or not) to handle a request, upstream is actually the exiting phase of the call stack. I copied the term from this documentation (search "cascading") https://koajs.com/

Incidentally, it reflects on plugins' middlewares.

3. a plugin at the moment can play with authentication, I suppose, but I'm not sure to what extent. Are you trying to achieve something and failed? Consider opening a dedicated issue for this.

4. that's probably my fault, I'm sorry. I tend to regret some commits I already pushed, and instead of having more commits to solve stupid errors I are recent and unreleased, I prefer to amend past commits. I think people approaching the repo will also benefit from this, but I suspected it would cause some annoyance on who already cloned.
I know I will have to stop this behaviour before or later, I postponed it because I'm still the only one on the repo, and I suspect the solution is just to --force the pull. I don't want to just ignore this problem, so let me know if this works for you.

**Comment by NaitLee** [comment]
Thank you 😄

For plugin auth, I think I won't really do it in a short time.
It seems possible via any frontend,
but I didn't see backend could directly do it by HFS code (HFS auth api functions needs a ctx parameter).

*(possibly could ignore the later case? frontend maybe already enough)*

**Comment by rejetto** [comment]
You mean  frontend only authentication?
It doesn't make sense to me

**Comment by NaitLee** [comment]
Maybe I've used wrong terms. Let me try explain:

By "frontend" I mean to do auth via HFS "frontend api" entry, i.e. post auth data to `/~/api/loginSrp1` (and 2) with ajax request
and "backend" mean plugin communicate directly with HFS code (so in this scenario plugin have its own api entry)

Think about a custom frontend plugin. The question is, could/should it implement its own auth method?
(just leave a question. I currently don't think I will do it, concerning security)

**Comment by NaitLee** [comment]
> and I suspect the solution is just to --force the pull. I don't want to just ignore this problem, so let me know if this works for you.

Yes it worked 😁

**Comment by rejetto** [comment]
cool!
For the "frontend plugin", if it is a plugin it should leave auth to the rest of the frontend.
If something useful is missing we can talk about it. I'm closing here, in case open a specific issue with a single concern.
