### ISSUE TITLE
Admin interface have extra resource loaded from Internet

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#38]
One is (yet) Google font. Another is `forge.min.js` from `unpkg.com`... :)

**Comment by rejetto** [comment]
is this a problem?
The google font should not be a strict dependency, as the interface is supposed to use Arial as fall-back.
File forge.min is used only if you try to login with http (not https), and it's 275KB, therefore it should be a problem only for people using https + login + no internet. As a side note, this could technically be addressed with a plugin.

**Comment by NaitLee** [comment]
I mentioned Google many times that, in regions without access to it, it will block the page load until timeout (approx. 1 minute in typical browsers). Before that it's a function-less blank page.
It's a *very* compact to experience of non-technical users.

Ok forge is reasonable... but do localhost (loopback network) really need it?

**Comment by rejetto** [comment]
Ok, I will take care of the font soon.
forge.min I will consider my options, like having it locally somewhere.

**Comment by rejetto** [comment]
can you tell me if you are personally failing at loading that css?

for a moment i had downloaded the css, but then i realized that it refers to more online resources, and getting all those files was too much in size.

I've found this method to avoid the problem with the css https://web.dev/defer-non-critical-css/
failing in loading it should be no big deal, it just falls back to arial. Right?

**Comment by NaitLee** [comment]
Yes, and it's a long timeout, rather than instant fail.

I've tested the `link preload` mentioned in that article, with a simple html page.
It seems working well, on this problem.

I still think external font is not important. Both Segoe UI (Windows) and Noto Sans (Linux & Android) are beautiful 😜

**Comment by rejetto** [comment]
Sure.
What we got here is the default setup of the UI library, not something I personally designed, but that's our starting point.
I suspect that roboto here is used because it is the default font for Android, that is closely related to Material design.
My Windows 10 has roboto already installed, by the way.
I may just remove the external loading and rely on this list, it should make no harm as we don't need to be pixel-perfect:
Roboto, "Noto sans", "Segoe UI", "San Francisco", "Helvetica Neue", Arial, sans-serif

**Comment by rejetto** [comment]
should be fixed in 0.22
LMK

**Comment by NaitLee** [comment]
Yes 🙂
