### ISSUE TITLE
Login Issue: Extra charcter space at the end of username.

### ISSUE THREAD

**Issue by GeorgeGeorgeGe** [rejetto/hfs#380]
Please note that any extra space character at the end or the beginning of an correct username will cause the error "Invalid Credentials".
please check.

Thanks in advance.

**Comment by TEA-Time1** [comment]
Sounds to me like a space is a valid character in a username, so it needs to work like that, and HFS shouldn't be messing with what was typed anyway. Otherwise Tim_ would be trimmed to Tim and then you have an invalid username even though you typed Tim_. Solution: avoid unnecessary space characters. 🙂

**Comment by rejetto** [comment]
I accept the complain, most people don't want spaces at the end and are confused when it happens.
So, as a default behavior I will remove the space, at least for the username.
If someone will need the other behavior, I will consider to have it as an option.

**Comment by rejetto** [comment]
fixed in https://github.com/rejetto/hfs/releases/tag/v0.49.0-alpha4

**Comment by GeorgeGeorgeGe** [comment]
Thanks a lot.
