### ISSUE TITLE
How to set the hiding of a sub file or folder in a shared virtual folder?

### ISSUE THREAD

**Issue by dafeifei0218** [rejetto/hfs#390]
How to set the hiding of a sub file or folder in a shared virtual folder?

Like the old version:
![image](https://github.com/rejetto/hfs/assets/10148878/c4059761-fbdd-49a0-9dea-6dfc4ec22434)

**Comment by rejetto** [comment]
now it's the "Who can see" setting
<img width="367" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/602c821b-af37-446e-888d-41fbfea71689">

**Comment by dafeifei0218** [comment]
This way, only the current shared directory can be set. How can I set the subdirectory to be hidden?
![image](https://github.com/rejetto/hfs/assets/10148878/96297aed-6c38-43bd-93a0-3f51f2702ab8)
D: FTP
There are also folders in the directory
/Gongxiang
/SW-21
/SW-8800
/SW-9000

**Comment by rejetto** [comment]
it is supposed to hide subdirectories as well.
that's the meaning of the "same permission for folder content" underneath.

**Comment by rejetto** [comment]
i noticed there's a bug in the interface if you change from "same permission" to "different permission", but that's not what you want. I'm telling just to warn you in case you see something strange playing with it.
I will publish a fix asap.

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.49.1
this should do it

**Comment by dafeifei0218** [comment]
Not what I want, I want to set the display or hiding of sub folders separately, just like the old version.
If set to anyone, subfolders will not be displayed in myFTP.

**Comment by rejetto** [comment]
quick solution:
1. click "MyFTP"  <img width="61" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/7f63b1f9-0275-4f7e-9218-2b5bce9ae37d">
2. click "Add"
3. click "from disk"
4. select all the folders you are missing using the checkboxes on their left <img width="102" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/e94badd6-f1af-4c1b-bc4e-bc287a4d48d3">
5. click "select" blue button


longer explanation:
looking closer at your screenshot, i see that your structure is *copied* in the virtual file system (i can tell by the color yellow).
This happened when you added the first folder. HFS 2 asked if you wanted to copy the structure of files (all virtual), or not (keep it to disk). At the time, you opted for copying.
While "copied" made things easier initially, it can a problem if your files are added/renamed on disk, because HFS won't show them. This is ok only if your structure never changes, or change very rarely.

The difference that made confusion is that HFS 3 is not offering you (at the moment) to copy the structure. 
With my istructions you make the copy, but just the first-level folders, and that's better, because if files inside are added or renamed, your server will stay up-to-date.
I have to understand what's the best solution to make this thing easier, yet.

There is also another solution, involing "masks", but in the general case I don't advice you for it.

**Comment by dafeifei0218** [comment]
Yes, that's fine. This is only the first level directory, it's troublesome to hide folders in more subdirectories.

**Comment by rejetto** [comment]
yes, it takes some work to do it like this.
I may think of a better way in the future.

There is currently an alternative but tricky way, as I was mentioning, that's using the "masks" field.
With masks you can enter all the folders you want just 
masks: maps a file mask to a set of properties as the one documented in this section.
The syntax is a bit tricky, but the result is very powerful. For example you can hide folder2 under folder1, and all mp3 files under folder3/folder4, using this syntax

```yaml
"folder1/folder2|folder3/folder4/*.mp3": 
  can_see: false
```

https://github.com/rejetto/hfs/wiki/Masks-field
