### ISSUE TITLE
cant turn off inheriting for index.html option

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#493]
![unnamed](https://github.com/rejetto/hfs/assets/90262580/977d50b5-5e6d-4701-a452-be255ecf1119)

**Comment by rejetto** [comment]
i'm not sure this is a common need worth a dedicated control, so i guess we should leave this to "masks".

Since the setting for that option is "default", as one can find in the documentation, if you want turn off inheritance you can
```yaml
"*":
  default: ""
```

if you want to stop just 1 folder, it's "folder1" instead of "*", or "subfolder/folder1" it it is not directly child of the folder.

But if you really have this specific folder1, one can also avoid "masks" and add folder1 to the main folder, and set the option the usual (graphical) way.
