### ISSUE TITLE
How to upload a file

### ISSUE THREAD

**Issue by elllectrum** [rejetto/hfs#546]
How do I grant permissions to upload a file to the server? I can't find this setting, please help.
![image](https://github.com/rejetto/hfs/assets/64004342/16076f2f-8fa0-4cd9-a64f-bb1be9462528)

**Comment by rejetto** [comment]
you cannot upload to the selected folder because that folder is not on disk.
You should set permission for the other folders that I can see your screen.

I'm not sure what is best for the user here.

I could show the upload-permission field but disabled, and some information on why it is disabled.

Or I could show it, working, and let you set permissions on the folder even without disk. That would not affect that folder but  make sense for subfolders, as they inherit permissions, and so you set it once and for all.

At the moment I'm not allowing you this because people could get confused when they try to access that same folder they set permissions (root in this case) without seeing the upload button (that wouldn't be displayed because it's not technically possible to upload without disk).

**Comment by elllectrum** [comment]
I understand that permissions should be given for a specific directory, not for the root directory. Thank you for the response. Everything worked out.
