### ISSUE TITLE
Root permissions

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#56]
**Describe the bug**
Set to ROOT folder permissions to "Any account (login required)" not working: root dir always shown to guests =\

**To Reproduce**
1. Set root folder permissions to "Any account (login required)"
2. Enter to root on frontend without account

**Comment by rejetto** [comment]
you are not saying what "permission" you are talking about,
but since in the browser the root only presents you with the "who can see" permission I'm sure you are talking about that.
That's expected to hide files, not to prevent access to the folder.

If you go to another folder (not root) you'll see you have another permission (who can download), to prevent access completely.
Anyway, this difference is because the root was previously unable to handle this other permission.
Now (version 0.23) it is, but I forgot to update the browser part, so you are not seeing the field.
You can
- wait for new version that will fix this problem in the browser
- do it manually: edit file config.yaml and set `can_read` instead of `can_see` for the root element. If you already set as you said you should already see the "can_see" and you can just rename it.

**Comment by rejetto** [comment]
if you read the small text under that field you'll read this

> but will still be accessible if you have a direct link

**Comment by 6elkir** [comment]
may be hide web interface if user have not access to dir? or require login from http authorization...

**Comment by rejetto** [comment]
what you are suggesting is exactly what I'm doing, but you didn't set the correct option, because that option is displayed (bug), and you set another.
If you don't want to wait for next release you can edit manually as I said.

**Comment by rejetto** [comment]
ok, i decided to publish a version with a fix
https://github.com/rejetto/hfs/releases/tag/v0.23.1

see if it's good
