### ISSUE TITLE
antibrute plugin

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#577]
it delays even a successful login after having a failed attempt

**Comment by W-i-n-7** [comment]
oops this should have been bug report sorry

**Comment by rejetto** [comment]
that's how it is supposed to work, otherwise it would not be effective for security.
you make am http request for login, and if it doesn't respond shortly you know it's wrong, so disconnect and make another request.
The only way to force waiting during a malicious attempt, is to delay even in case of success.

**Comment by W-i-n-7** [comment]
> that's how it is supposed to work, otherwise it would not be effective for security. you make am http request for login, and if it doesn't respond shortly you know it's wrong, so disconnect and make another request. The only way to force waiting during a malicious attempt, is to delay even in case of success.

oh that makes sense now i know
