### ISSUE TITLE
can not use"Internet download manager" login dialog to login HFS after session expired

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#58]
A downloader software call "Internet Download Manager", or short for "IDM", have ability to login in some kind of server that do not need to run in browser. But this feature didn't work in HFS after session expired. the error code is http "401" unauthorized with HFS user name and password. Hope can have a solution to deal with that. Thank you so much!

**Comment by rejetto** [comment]
what hfs version, what idm version

**Comment by dzw13579** [comment]
> what hfs version, what idm version

HFS:0.22.0
IDM:6.40 build 11

**Comment by rejetto** [comment]
I can't find information about how IDM is supposed to deal with protected websites, what a server is supposed to do to be compatible.
If you find detailed information I can have a look at it and we'll see.
If you can't find it, you can ask their staff to provide it .

I'm not willing to install it since it's not free.
I tried [FDM](https://www.freedownloadmanager.org/) and it worked without a problem with protected files.

**Comment by dzw13579** [comment]
> I can't find information about how IDM is supposed to deal with protected websites, what a server is supposed to do to be compatible. If you find detailed information I can have a look at it and we'll see. If you can't find it, you can ask their staff to provide it .
> 
> I'm not willing to install it since it's not free. I tried [FDM](https://www.freedownloadmanager.org/) and it worked without a problem with protected files.

all right, FDM also work for me, I will chosing it in HFS files download instead of IDM. Thanks!

**Comment by rejetto** [comment]
I'm still interested in knowing what's the problem with IDM, if it's supposed to work.
In case someone finds information let me know.
