### ISSUE TITLE
When uploading multiple files, the files will be prefixed with hfs$ for a long time.

### ISSUE THREAD

**Issue by QinYueQwQ** [rejetto/hfs#604]
As the title says, when I try to upload multiple files at once, the newly uploaded files are prefixed with hfs$ and gradually grow in size until they reach the size of the file itself. This does not happen when uploading individual files.
In addition, uploading a batch of files of the same size on a server with a much more powerful hard drive than my PC seems to take longer to make the files available than when I test it on my PC.
![PR](https://github.com/rejetto/hfs/assets/147228519/aaadc158-4328-4c48-bd65-bbfc56a1e59d)

**Comment by rejetto** [comment]
files are always uploaded 1 at a time, doesn't matter if it's 1000s.
until the single file is completed, it has the hfs$upload- in the name.
after the single file upload is completed, it is immediately renamed, and it works on the next file.
this is not a bug, it's by design.
if you didn't see it with individual files, is just because it was fast and you didn't notice.

the hard drive speed will hardly make a difference, as normally the most important thing is the network speed.

**Comment by QinYueQwQ** [comment]
I understand, thanks for your reply!
