### ISSUE TITLE
Tray Icon doesn't work right (hfs doesn't open/no menu)

### ISSUE THREAD

**Issue by d-tool** [rejetto/hfs#628]
Hello
Since update to v2.4.0 the tray icon doesn't work right with wine and also I can't open it anymore with click on tray, so I can't configure anything without restart. Also minimizing is the wrong decision cause I can't get it up again..

1. Run HFS with wine on Debian
2. Click on the tray icon to open HFS or the menu 
3. See that nothing happens

Nothing happens when you click on the Icon to open the menu or to open the window itself.
This leads to having to restart the server every time you want to see it or config something.

The menu should open and I think it was a double click and the window itself opens.

 wine Version:
 wine-9.10 (Staging)
 
Debian:
Debian GNU/Linux 11 (bullseye)
Linux version 5.10.0-30-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.218-1 (2024-06-01)

HFS <3 thanks!!!

**Comment by rejetto** [comment]
hey, i don't support HFS 2 anymore, so I cannot accept this request.
The update to 2.4 was initially made when i thought that version was not affected by the huge security problem that was recently published. But it turns out I was wrong.
My suggestion is to use HFS 3 that you find in this page
https://github.com/rejetto/hfs/
and by the way, it runs on linux without wine

**Comment by d-tool** [comment]
Hi and thanks for your answer. Then I missed to update. Also I mean I already used the Linux Version. 
Whatever, thanks for the hint, will use that now. Sorry for the mistake
//edit: damn that I missed it, so much better. thanks
