### ISSUE TITLE
Logout not working Properly Sometimes

### ISSUE THREAD

**Issue by POPIT-SOLUTIONS** [rejetto/hfs#654]
1, The issue has been encountered multiple times: if we log out from any user and make changes to the admin panel from the same or a different device, refreshing the page where we first logged out automatically logs us back in with the previously logged-in user ID.

2, When we log out directly from a directory that only a single user has access to, the page does not redirect to the login page.
![image](https://github.com/rejetto/hfs/assets/168815722/eb4b755a-3970-4d59-a29a-f7de08f526cb)

3, (Suggestion) If we attempt to log in from the page shown in the image above with a different user (who doesn't have access to that directory), it only shows "nothing here". It would be better if it automatically redirected to the root folder. Note: this only occurs when "redirect to folder" is not set in the user settings.

4, After the new update RC15, there is a "';}" visible on the top left of the user interface panel.

**Comment by POPIT-SOLUTIONS** [comment]
5, (Suggestion) Scrollbar in the dark mode is in light theme

**Comment by rejetto** [comment]
please if you have multiple problems, open multiple issues, as this is harder for me to manage.

1. if you login in the admin-panel, you are also logged in the frontend. If you don't want that you can use a different browser, or private/incognito.

2. this can depend on the specific permissions. What happens if after logout you refresh, do you get the login? Also, please screenshot the permissions of that folder.

3. hfs is not redirecting to root because root can also require login. If your root is public, you can customize hfs login to provide a link to it. (admin-panel > custom > before login)

4. i don't see that in mine. It is possible that you added it by accident. Check admin-panel > custom html. You need to check only sections with an asterisk.

5. it is already so, but your browser is probably not compatible with it. Please specify what browser you are using.

**Comment by POPIT-SOLUTIONS** [comment]
First of all really sorry for mixing up all this  together

1, Ok, i thought admin panel and frontend were support , thankoyou 
2, if logout and refresh nothing happens refresh to same page
    Hereby attaching permisson for the folder
![PERMISSION](https://github.com/rejetto/hfs/assets/168815722/685bb95b-9ebe-4381-8a2b-e44947e71414)

3, OK
4, only i have edited unautharized page and Befor Login page and only they have asterisk on them .
   some thing is not working properly in my server, yesterday "';}" only this was showing 
  but today a huge portion of code is visible in frontend 
![frontend](https://github.com/rejetto/hfs/assets/168815722/a9627fd8-4785-4b20-a40a-cc8abf67798b)

  also admin panel have scroll bar and scrolls down as some black portion is visible as of the image attached
![admin panel](https://github.com/rejetto/hfs/assets/168815722/1ba79185-bb68-48ef-ae84-0f9ab3a2335b)

5,already tried with multiple browsers and each have the same issue  
   i have already tested in 
   Google Chrome
   Version 126.0.6478.127 (Official Build) (64-bit)
   Microsoft Edge
   Version 126.0.2592.68 (Official build) (64-bit)

**Comment by POPIT-SOLUTIONS** [comment]
after rplying and some refreshes change the code visible in frontpanel as 
![frontend01](https://github.com/rejetto/hfs/assets/168815722/5fae3138-bbb2-4c8d-a0b3-1bc764d3a289)

**Comment by rejetto** [comment]
4. i'm studying this now

**Comment by rejetto** [comment]
2. you set the wrong permissions. You set "access list" to "anyone", so anyone accesses and no login is required. You just restricted what users "see", so they see nothing.
4. ok, it was a bug in hfs but it happens only when using file-icons plugin. I just prepared the fix.
5. i use same chrome on windows and there is no problem with the scrollbar, so i suspect this is caused by problem 4.

**Comment by rejetto** [comment]
if you want to access the fix now without waiting next release, use the right-click update ;)
https://github.com/user-attachments/files/16012626/hfs-windows-0.53.0-rc15.1.zip
in case you test it, let me know how it goes

**Comment by POPIT-SOLUTIONS** [comment]
Thank you, Rejetto.

I have corrected the permissions. Additionally, I suspect that issues 4 and 5 were caused by the file-icon plugin. I will update the server with the fix you provided and keep you updated.

**Comment by POPIT-SOLUTIONS** [comment]
updated with fix provided by you . but still showing "";--download-counter-where: "menu";--file-icons-folders: "E:\\POPIT CLOUD\\ICONS\\folder.png"; --file-icons-files: "";--thumbnails-showTilesInMenu: true; --thumbnails-videos: true; }" this code in frontend panel

**Comment by rejetto** [comment]
ok thanks.
the problem is similar to the previous one but different and requires different solution on my part.
It is caused by the presence of "</style>" inside the mark-news html.
i'm about to fix it, but you can solve immediately without waiting for my fix, by moving only the "style" part to "custom html" inside the "style" section.
this doesn't only work-around the problem, it's also more correct as a result, because the that style is supposed to be only one, while right now it is duplicated for every element in the list. (which is not critical, but not perfect either)

**Comment by rejetto** [comment]
anyway, this is supposed to fix it
https://github.com/user-attachments/files/16027130/hfs-windows-0.53.0-rc15.2.zip

**Comment by POPIT-SOLUTIONS** [comment]
Thank you, Rejetto.
 I tried both methods, and both work. I think after the new version, no more plugin configurations will affect the server.
