### ISSUE TITLE
404 home root in new window

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#66]
**Describe the bug**
After reboot my CLIENT pc i get 404 on white window in root =\ To reproduce this bug - clear temp dir on windows os

**Comment by rejetto** [comment]
How can I reproduce your problem?

**Comment by 6elkir** [comment]
My bug occurs after some time of server work, OR if you manually clean the OS temp directory c:\windows\temp

**Comment by rejetto** [comment]
i tried emptying the temp folder on HFS' computer, also I've been running my server 24h for days, and I've found no problem.
So this is not enough to reproduce it, sorry.

**Comment by rejetto** [comment]
try taking a screenshot with the browser console open

**Comment by rejetto** [comment]
also look at hfs' console if any message could be useful, and see the "debug.log" in hfs folder

**Comment by 6elkir** [comment]
Client screenshot: https://share.dvor-net.ptz.ru/07TOsaYpUX.png
Servel log: https://share.dvor-net.ptz.ru/R1Gr18hgBK.png
Log file: https://share.dvor-net.ptz.ru/debug.log

**Comment by rejetto** [comment]
i suggest to hide your address from the screenshot.
I suspect by deleting that temp folder (not \windows\temp, the one reported in the log) you may be interfering with hfs.exe, because it is using a tool called "pkg" to produce the exe and it seems involved in the printed path.
can you avoid wiping that folder and see if it is solved?

**Comment by rejetto** [comment]
how are you running hfs ? double click on exe or what?

**Comment by rejetto** [comment]
it seems possible for this issue to be related to https://github.com/vercel/pkg/issues/1439

**Comment by 6elkir** [comment]
> how are you running hfs ? double click on exe or what?

Double click on exe)

**Comment by 6elkir** [comment]
Some time later server works and i get 404 blank now =\ Temp dir i not clear. Bug return some time later.

**Comment by rejetto** [comment]
you said \windows\temp and that's what i tried first time, but now we know the folder is another, and if i delete _appdata\local\temp_ the problem is reproduced successfully!
My best guess is that, on your computer, something is clearing the temp folder after a while, causing the problem.
Have you any clue? Do you think you can stop it?
I have no idea if the clearing is "legit" or what. I tried to ask for enlightenment https://github.com/vercel/pkg/discussions/1675  
Maybe it's a software you installed to "optimize" your computer. Consider that it doesn't happen on my Windows 10, so would exclude it's a default of the system.

**Comment by 6elkir** [comment]
Ashampoo WinOptimizer work on server in background, but on prev versions HFS this bug is not reproduced

**Comment by rejetto** [comment]
what versions are you talking about? hf2 or hfs3 ?
please try to disable it for some time and see if the problem is related to it

**Comment by 6elkir** [comment]
version 3 last

**Comment by rejetto** [comment]
Another test that you can make, other than disabling for a while WinOptimizer, is to choose a previous version of HFS that you think doesn't have the problem, and try it now.
We cannot know if your problem was triggered from an update of HFS, or an update of WinOptimizer, or some other thing, so this is the only way I can think of.
Let me know if you have results of these 2 tests.

**Comment by 6elkir** [comment]
WinOptimizer disabling not help. Some time (1-3 hours) bug reproduced. On HFS 0.23.0 this bug not reproduced.

**Comment by rejetto** [comment]
I've studied changes in 0.23-0.24 and cannot find anything that could possibly cause this problem.
I also ran 0.23 to verify that it is creating the same files in the same temp directory
\Users\USERNAME\AppData\Local\Temp\pkg-RANDOMLETTERS\

I deleted those temp files and I'm seeing "not found". Deleting those temp files is affecting any version since 0.10, because that's where they were introduced. The reason of these temp files is to have a single exe file for the program.
Whatever the problem is, it is very likely to be some "other" program deleting temp files.

As an additional information, I know what files are those: are the ones that are sent to the browser to show the pages (html, etc). So I considered the possibility that some change in those files triggered an antivirus that is deleting them. I just verified and 0.24 didn't make any change to those files, they are basically the same of 0.23.

My HFS 0.24.1 has now passed 3 days of uptime.
At the moment I really have no other clue.
I will ask on the telegram group if anyone is having your same problem.

**Comment by rejetto** [comment]
so, is the problem with 0.24 reproduced in 1-3 hours ?
how long did you try 0.23 without having problem?

**Comment by 6elkir** [comment]
May be move temp directory to prog dir? If someone flush OS temp - moving to prog dir must help...

**Comment by rejetto** [comment]
that's not me doing it so I have no power over it, while I'm using this tool.
I already suggested something, I hope someone will answer. 
https://github.com/vercel/pkg/discussions/1675#discussioncomment-3068657
I'll wait a few days, and if I don't get an answer I'll consider my options.

**Comment by rejetto** [comment]
introducing a cache for those files should be a practical workaround
https://github.com/rejetto/hfs/releases/tag/v0.24.3
LMK
