### ISSUE TITLE
the plugin list does not load

### ISSUE THREAD

**Issue by OlevO1** [rejetto/hfs#713]
**To Reproduce**
1. Go to 'Plugins'
2. Click on 'Search Online'

**Describe the bug**
loading... and: 
![image](https://github.com/user-attachments/assets/4323a895-39e8-4dab-a91c-26161eed2c1c)

**Environment (please complete the following information):**
 - OS: Win 10
 - HFS Version: 0.53.0
 - Browser: Chrome

**Comment by OlevO1** [comment]
and check updates: 
![image](https://github.com/user-attachments/assets/d7067f7f-e5e6-49c6-b96f-1151aef2742b)

**Comment by rejetto** [comment]
it's like your HFS cannot reach github.com

Is your HFS running on the same computer you use to write here on github?

**Comment by OlevO1** [comment]
nope, hfs is runnning on vps

**Comment by rejetto** [comment]
ok, then something is preventing your HFS from talking to github.
i can improve the error messages, but it's not a bug.

**Comment by OlevO1** [comment]
and how can I solve the problem?

**Comment by rejetto** [comment]
sorry, i'm not good at managing vps or linux.
ask your vps provider if they have some block/firewall that you can disable.

**Comment by OlevO1** [comment]
can I get a link to the plugin list/plugins? so I can download them manually

**Comment by rejetto** [comment]
yes, but i suggest you to solve the problem, as otherwise you won't get plugins updates, for instance.
also, you won't get warnings in case the version you use is found to be vulnerable to attacks.

https://github.com/rejetto/hfs/wiki/Plugins#online-directory

**Comment by OlevO1** [comment]
ty

**Comment by Xingeqwd** [comment]
Ha! 
I have this problem too. The program can't find any extensions online. 
It seems that I can only install them manually.

However, the machine running hfs can access github directly, 
so it's a bit strange that hfs can't access it

It's not a big matter for me. Because I am good at Windows and Linux.

I was just passing by! Just said this by chance. 
By the way, this program is a masterpiece！


（
I think I should open an issue, regard i have the same problem, but the symptoms are different（upgrade not goes error）
 let me do it tomorrow.....

Sorry to bother you!
）

**Comment by rejetto** [comment]
@Xingeqwd thanks, and feel free to open a new issue and we'll see what we can do about it
