### ISSUE TITLE
If it's possible to add "copy / link" in addition to "cut"?

### ISSUE THREAD

**Issue by buddingworld** [rejetto/hfs#716]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
just the similar action like "cut"

**Describe alternatives you've considered**
sometimes a file can be in different directory(s) without upload again or occupy an extra size of disk?

**Additional context**
i dont know if it's hard or necessary or not,but it may be useful sometimes i think

**Comment by rejetto** [comment]
it's not clear if you want a "copy link" like the one you get if you right click with the browser, or a "copy file" that will duplicate the file to a different folder of the server

**Comment by buddingworld** [comment]
> it's not clear if you want a "copy link" like the one you get if you right click with the browser, or a "copy file" that will duplicate the file to a different folder of the server

sorry but it's "copy file" or "link file" that i described above.just like the "cp" or "ln" command in linux

**Comment by rejetto** [comment]
ok, now i get it, copy/link.
while cut needs delete permission, copy wouldn't: just pasting would require permission, let's say upload, but pasting happens after you changed folder.
So, basically copy wouldn't need any special permission. 
But I don't want it to be offered to all users by default, it would be a bit confusing for basic use cases. There are a lot of read-only servers out there, a user accesses them only to download stuff, but then he sees "copy" command (which cannot be pasted anywhere because you don't have upload pemissions) and wonders what's that about.
Unless i have a good design i'm not going to introduce this feature, but it may be a good idea for a plugin.

**Comment by buddingworld** [comment]
> ok, now i get it, copy/link. while cut needs delete permission, copy wouldn't: just pasting would require permission, let's say upload, but pasting happens after you changed folder. So, basically copy wouldn't need any special permission. But I don't want it to be offered to all users by default, it would be a bit confusing for basic use cases. There are a lot of read-only servers out there, a user access them only to download stuff, but you see "copy" command (which cannot be pasted anywhere because you don't have upload pemissions) and wonder what's that about. Unless i have a good design i'm not going to introduce this feature, but it may be a good idea for a plugin.

thx for reply,maybe it'll be confusing sometimes or for some users,but it's useful in some situations such as we teacher can share different folder to  colleagues by according to subject or grade.btw,it can be aside with "cut" functions. if the new feature can be add someday by hfs or by plugins i'd be appreciated.hfs is a nice project~

**Comment by rejetto** [comment]
i see. for the moment i'm working to make this a plugin

**Comment by rejetto** [comment]
i'm almost done, but it will require 0.54

**Comment by rejetto** [comment]
ok, it's available for HFS 0.54.0-alpha2
