### ISSUE TITLE
Selecting files to download as an archive

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#80]
It would be cool to be able to select some of them with checkmarks in the list of files and by clicking the "Download archive" button, download not the entire directory, but only the previously selected files. As for me - it will be very convenient.

**Comment by rejetto** [comment]
this feature is already available, but you have to click "filter list" button
<img width="373" alt="image" src="https://user-images.githubusercontent.com/1367199/202153924-57fa66f8-204f-4394-8f85-9962724da7be.png">

**Comment by rejetto** [comment]
I understand it is not clear that you have to click "filter list".
I made it so because I didn't want to clutter the list with the checkboxes all the time.

Maybe if extend this message
<img width="333" alt="image" src="https://user-images.githubusercontent.com/1367199/202156901-7fec8436-b46b-42be-9084-0bb46a07d4dd.png">

specifying that you can get only some files if you click "filter list", more people will find it.
Or keep same message but offer a third button "select some files".

Not a perfect solution, tho.
