### ISSUE TITLE
HFS Docker option to make self signed cert network errors and connection erros. Stop start docker workaround

### ISSUE THREAD

**Issue by bmartino1** [rejetto/hfs#802]
When using the docker form of HFS and making a ssl certificate in the admin interface. you may get network error and connection error after admin interface makes the certificate. while stopping and starting, the docker fixes the issues.

This is still a bug... this may require a fix either in hfs on how the certificate is made or in the dockers docerfile to add a option/ fix network error.

I'm not sure where nor why this breaks.

**Comment by rejetto** [comment]
i've found force_https is on by default, so removing it from your envs didn't change a thing :)

default values are documented in config.md, but this was changed at some time and i forgot to update the doc. 🫠

anyway, this case should be handled better by the web interface, as it's very confusing as it is. So, i will consider a bug of the UI.
I've never seen it before because i made my tests with localhost, and it's not affected by force_https.

**Comment by bmartino1** [comment]
good to know. Thank you

I may add force https false to set it disabled for time being and have users change the value. after ssl cert is installed. Thank You

**Comment by rejetto** [comment]
ok i've managed to fix the problem with the error
