### ISSUE TITLE
Store column preferences for Logs page

### ISSUE THREAD

**Issue by cbr00t** [rejetto/hfs#817]
HFS Version: **0.55.0 Alpha 1**
OS: **Windows 11**

1) Logs panel no longer shows Username and Country columns and not remembers my column selection.

2) Even I show Username column, there are no Username in log entries.

![image](https://github.com/user-attachments/assets/66c2555e-4b6c-4ca5-a363-0b2951a5fe02)

**Comment by rejetto** [comment]
1. why do you say you don't see the columns? i can see them in your second screenshot.
in your first screenshot those columns are collapsed inside "address" column, as you can see from the flag. HFS does so based on the space available on the screen.

2. if the username is empty it guess it's because the user was not logged in, right?
did you try to log in and see if the username appears?
it works fine on my computer
![image](https://github.com/user-attachments/assets/f1ad836d-e705-4e92-a606-a785c3dcb9f2)

**Comment by cbr00t** [comment]
What I mean about columns: It's about columns that are turned off by default. I make them visible, but when I enter the Log screen again, they return to their original state. 👎🏼

It would be nice to save the displayed column settings (on the browser localStorage, for example).
I especially look at the Username and Country columns in the Log panel all the time. 🥇


There were logged-in users in some lines in the logs in the second screenshot, but they did not appear in the Username field in the log records.

Then a new version was released very recently after these log records were created (the current Alpha1 version) and I installed it. Now when I tried it, I saw that the username appeared 👍🏼

**Comment by rejetto** [comment]
yes, admin-panel is not even trying to remember your columns selection. Not actually a bug.
I can consider using localstorage. I'm not sure if config file is better.
I'd like to understand why you enabled country column when its content was already visible inside the address colum.

**Comment by cbr00t** [comment]
Country ... yes it's visible right there i saw it later :)
But username not.

Massimo Melina ***@***.***>, 24 Kas 2024 Paz, 00:09 tarihinde
şunu yazdı:

**Comment by rejetto** [comment]
yes, username too, same as country, inside the "address" column.
it's an optimization done by hfs when the screen is not wide enough, as it's more compact.

**Comment by rejetto** [comment]
fixed in 55 alpha2
